### PR TITLE
Remove extra "rtsp_servers.html" file

### PR DESCRIPTION
**Pull request by hdm**
## Description

This removes an extra `rtsp_servers.html` file that was added by mistake on a previous PR.

## Motivation and Context

This is a minor issue

## How Has This Been Tested?

Removing the extra file does not break anything,

## Types of changes
- Bug fix (non-breaking change which fixes an issue)

The branch history is noisy (finally lining back up with master), but the only change in this PR is to remove the extra/misplaced .html file.

## Checklist:

- [x] I have updated the documentation accordingly (or changes are not required).
- [x] I have added tests to cover my changes (or new tests are not required).
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tsellers-r7** [comment]
@hdm - AFAICT, `rtsp_servers.html` doesn't exist in `master`.  Perhaps this is a local only change?

**Comment by hdm** [comment]
Phew, thanks for checking! Must have been an artifact of all the branch merging here

**Comment by tsellers-r7** [comment]
I've just released 2.3.7, anything you need to get in while I'm working on things?

**Comment by hdm** [comment]
Nothing pending right now, but we have a bunch of fingerprinting backlog work to get through, likely starting again next week.

**Pull request closed without merging**
