### PR TITLE
Add some fingerprints

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by hdm** [comment]
Does anyone need help reviewing this PR?

**Comment by hdm** [comment]
This has been merged into github.com/RumbleDiscovery/recog  (main).

**Comment by tsellers-r7** [comment]
@jvoisin - Thanks for the contribution, sorry for the delays with reviews.

**Comment by tsellers-r7** [comment]
FYI @jvoisin @hdm - I've tweaked a few vendor names / CPE values in order to enable CPE autogeneration:

https://github.com/rapid7/recog/pull/349

**Pull request merged**
