### PR TITLE
Additional Apple devices

### PR DESCRIPTION
**Pull request by hdm**
## Description

This PR includes a number of new Apple MDNS fingerprints (laptops, desktops, servers, devices, mobile phones, tablets, TVs, and homepod).

## Motivation and Context

This resolves missing fingerprints for a wide range of Apple products.

## How Has This Been Tested?

Use of rspec, recog_verify, and testing against real device fingerprints.

## Types of changes
- Support for a wide range of Apple devices

## Checklist:
- [X] I have updated the documentation accordingly (**changes are not required**).
- [X] I have added tests to cover my changes (or new tests are not required).
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by hdm** [comment]
jRuby failure seems unrelated:
```
load error: childprocess/jruby -- java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.io.FileDescriptor sun.nio.ch.FileChannelImpl.fd accessible: module java.base does not "opens sun.nio.ch" to module jruby (LoadError)
```

**Comment by gschneider-r7** [comment]
Opened #238 for JRuby failure.

**Comment by hdm** [comment]
Anything I can help with to merge this to master? We have a few other projects like this and would be happy to maintain a fork if working on these in larger batches is easier.

**Comment by hdm** [comment]
Thanks yall!

**Comment by tsellers-r7** [comment]
Thanks for the contribution @hdm   I apologize for the delayed review.  Version 2.3.3 of the gem has been released on RubyGems.

**Pull request merged**
