### PR TITLE
Add a way to detect zimbra via cookies

### PR DESCRIPTION
**Pull request by jvoisin**
This can be tested here: https://mail.zimbra.com/

### CODE REVIEW

**Comment by hdm** [comment]
Julian - it would be easier for the team to manage this as a single pull request instead of one per application. Would it be possible to consolidate these?

**Comment by jvoisin** [comment]
I explicitly split everything into several pull-requests to make the reviews straightforward, but I can merge everything into a single one if you prefer.

**Comment by hdm** [comment]
A single PR would be much easier for the team to review in a reasonable amount of time (all code changes require multiple approvers, so the overhead of each pull request becomes quite large).

**Comment by jvoisin** [comment]
Done in #327

**Comment by jvoisin** [comment]
Closed in favour of #327

**Pull request closed without merging**
