### PR TITLE
EOL 1.9.3 support, fixes #26

### LINKED ISSUE #26: EOL 1.9.3 support
2/23/2015, 1.9.3 will be EOL.  Metasploit is also making this change (or maybe they did already -- I don't know for sure).

Recog should drop 1.9.3 support too.

### PR DESCRIPTION
**Pull request by jhart-r7**
Remove 1.9.3 from Travis
Set minimum ruby version for the gem to 2.1+
Bump recog version

I can still build the gem on 1.9.3 but it won't install:

```
$  gem build recog.gemspec && gem install recog-1.0.18.gem 
  Successfully built RubyGem
  Name: recog
  Version: 1.0.18
  File: recog-1.0.18.gem
ERROR:  Error installing recog-1.0.18.gem:
	recog requires Ruby version >= 2.1.
```

### CODE REVIEW

**Comment by gschneider-r7** [comment]
Shouldn't this be more than a "patch" version change? Anyone relying on semantic versioning will be surprised if they don't have Ruby 2.1+ installed and they pull this in. Should at least be a "minor" version increase in my opinion.

**Comment by limhoff-r7** [comment]
Post 1.0.0, an incompatible change requires incrementing the MAJOR version number, so that means the correct version for this change is 2.0.0.

**Comment by limhoff-r7** [comment]
For reference: http://semver.org/

**Comment by jhart-r7** [comment]
Agreed -- 2.0.0 is more appropriate.

**Comment by jhart-r7** [comment]
AFAIK, this is good to go.  If there are other reasons we shouldn't land this now, please speak up.

**Comment by hmoore-r7** [comment]
No problem here, we can start bumping Gemfile requirements once this is released

**Comment by jhart-r7** [comment]
@hmoore-r7, could you land this?  I'll follow up with the Nexpose side of the house to ensure that the new major version is fetched if you could coordinate similarly with Metasploit.  Thanks!

**Comment by hmoore-r7** [comment]
Sure thing!

**Pull request merged**
